"""doctor_id is nullable

Revision ID: 801827da3e79
Revises: a9e6c0fd6bf0
Create Date: 2021-05-27 22:59:25.773394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801827da3e79'
down_revision = 'a9e6c0fd6bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
